name: SwiftLint

on:
  # Run the workflow on each push and allow manual triggering
  push:
  workflow_dispatch:

jobs:
  SwiftLint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cirruslabs/swiftlint-action@v1
        with:
          version: latest
