name: SwiftLint

on:
  workflow_dispatch: # Allows the workflow to be triggered manually

jobs:
  SwiftLint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cirruslabs/swiftlint-action@v1
        with:
          version: latest