name: Publish CocoaPod

on:
  workflow_dispatch: # Allows the workflow to be triggered manually

jobs:
  publish:
    runs-on: macos-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Ruby and CocoaPods
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0 # Specify the Ruby version for CocoaPods

      # Install dependencies
      - name: Install CocoaPods
        run: |
          gem install cocoapods

      # Publish the pod
      - name: Publish to CocoaPods trunk
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          pod trunk push --allow-warnings
